# Generated by Django 5.1.1 on 2025-09-07 07:47

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=100, unique=True)),
                ('max_foreman', models.PositiveIntegerField(default=0)),
                ('current_foreman_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leader Quota',
                'verbose_name_plural': 'Leader Quotas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('nrp', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('leader', 'Leader'), ('foreman', 'Foreman')], default='foreman', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('SUPPORT', 'Support $ Fabrikasi'), ('TRACK', 'Track'), ('PLANT', 'Plant Coal Hauling'), ('WHEEL', 'Wheel')], max_length=100, null=True)),
                ('shift', models.IntegerField(choices=[(1, 'Shift 1'), (2, 'Shift 2')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('leader', models.ForeignKey(blank=True, limit_choices_to={'role': 'leader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foremen', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('leader_quota', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_user', to='dashboard.leaderquota')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.IntegerField(choices=[(1, 'Shift 1'), (2, 'Shift 2')], default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('activities', models.TextField()),
                ('Unit_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Hmkm', models.CharField(blank=True, max_length=100, null=True)),
                ('component', models.CharField(blank=True, choices=[('Component_1', 'Engine'), ('Component_2', 'Clutch - Couper'), ('Component_3', 'PTO'), ('Component_4', 'Transmisi'), ('Component_5', 'Final Drive'), ('Component_6', 'Travel - Axle'), ('Component_7', 'Steering'), ('Component_8', 'Under Carriage'), ('Component_9', 'Wheel'), ('Component_10', 'Frame & Guard'), ('Component_11', 'Electric'), ('Component_12', 'Brake'), ('Component_13', 'Suspension'), ('Component_14', 'Hydraulic'), ('Component_15', 'Pneumatic'), ('Component_16', 'Swing System'), ('Component_17', 'Attachment'), ('Component_18', 'GET'), ('Component_19', 'Vessel Assy'), ('Component_20', 'Generating Set'), ('Component_21', 'Dewatering Pump'), ('Component_22', 'Optional Accessories'), ('Component_23', 'Tank & Piping'), ('Component_24', 'AC'), ('Component_25', 'Stone Crusher'), ('Component_26', 'Daily Maintenance'), ('Component_27', '12 Mounth Service'), ('Component_28', '6 Mounth Service'), ('Component_29', '90 Days Service'), ('Component_30', '30 Days Service'), ('Component_31', '10 Dayts Service'), ('Component_32', 'PPA'), ('Component_33', 'PPU'), ('Component_34', 'PPM'), ('Component_35', 'PAP'), ('Component_36', '4000 Hour Service'), ('Component_37', '2000 Hour Service'), ('Component_38', '1000 Hour Service'), ('Component_39', '500 Hour Service'), ('Component_40', '250 Hour Service'), ('Component_41', '100 Hour Service (Inisial)'), ('Component_42', '50 Hour Service (inisial)'), ('Component_43', '100 Hour Dialy Check'), ('Component_44', 'Component Overhaul'), ('Component_45', 'Component Midlive'), ('Component_46', '20.000 KM Service'), ('Component_47', '15.000 KM Service'), ('Component_48', '10.000 KM Service'), ('Component_49', '5.000 KM Service'), ('Component_50', '2.500 KM Service')], max_length=100, null=True)),
                ('activities_code', models.CharField(blank=True, choices=[('SC', 'SC'), ('USC', 'USC'), ('ACD', 'ACD')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('foreman', models.ForeignKey(limit_choices_to={'role': 'foreman'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_track', models.CharField(blank=True, choices=[('PC1250', 'PC1250'), ('CAT395', 'CAT395'), ('DX800', 'DX800'), ('PC500', 'PC500'), ('PC300', 'PC300'), ('PC200/210', 'PC200/210'), ('D375', 'D375'), ('D155', 'D155'), ('D85', 'D85'), ('EPIROC DM30', 'EPIROC DM30')], max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('no_report', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.DateField()),
                ('WO_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('WO_date', models.DateField()),
                ('unit_code', models.CharField(blank=True, max_length=100, null=True)),
                ('problem', models.CharField(blank=True, choices=[('1000', 'Engine'), ('2000', 'Clutch System'), ('3000', 'Transmission'), ('4000', 'Travel Dive-Axle'), ('5000', 'Steering'), ('6000', 'Undercariage'), ('7000', 'Electric'), ('8000', 'Attachment'), ('9000', 'Periodical Services')], max_length=100, null=True)),
                ('Trouble_date', models.DateField()),
                ('Hm', models.CharField(blank=True, max_length=100, null=True)),
                ('title_problem', models.TextField()),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('part_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('nama_fungsi_komponen', models.TextField(blank=True, help_text='Jelaskan nama dan fungsi komponen yang bermasalah', null=True, verbose_name='Nama & Fungsi Komponen')),
                ('gejala_masalah', models.TextField(blank=True, help_text='Deskripsikan gejala masalah yang dihadapi', null=True, verbose_name='Gejala Masalah yang Dihadapi')),
                ('akar_penyebab_masalah', models.TextField(blank=True, help_text='Jelaskan akar penyebab masalah berdasarkan analisis', null=True, verbose_name='Akar Penyebab Masalah')),
                ('faktor_man', models.BooleanField(default=False, help_text='Faktor manusia sebagai penyebab masalah', verbose_name='Man (Manusia)')),
                ('faktor_material', models.BooleanField(default=False, help_text='Faktor material sebagai penyebab masalah', verbose_name='Material')),
                ('faktor_machine', models.BooleanField(default=False, help_text='Faktor mesin sebagai penyebab masalah', verbose_name='Machine (Mesin)')),
                ('faktor_method', models.BooleanField(default=False, help_text='Faktor metode sebagai penyebab masalah', verbose_name='Method (Metode)')),
                ('faktor_environment', models.BooleanField(default=False, help_text='Faktor lingkungan sebagai penyebab masalah', verbose_name='Environment (Lingkungan)')),
                ('tindakan_dilakukan', models.TextField(blank=True, help_text='Jelaskan tindakan yang telah dilakukan untuk mengatasi masalah', null=True, verbose_name='Tindakan yang Dilakukan')),
                ('tindakan_pencegahan', models.TextField(blank=True, help_text='Jelaskan tindakan pencegahan untuk mencegah masalah serupa', null=True, verbose_name='Tindakan Pencegahan')),
                ('dokumentasi_sebelum', models.FileField(blank=True, help_text='Upload gambar/drawing sebelum perbaikan (Max 1MB)', null=True, upload_to='analysis_reports/before/', verbose_name='Dokumentasi Sebelum')),
                ('dokumentasi_sesudah', models.FileField(blank=True, help_text='Upload gambar/drawing sesudah perbaikan (Max 1MB)', null=True, upload_to='analysis_reports/after/', verbose_name='Dokumentasi Sesudah')),
                ('foreman', models.ForeignKey(limit_choices_to={'role': 'foreman'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Report',
                'verbose_name_plural': 'Analysis Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('activity_reminder', 'Activity Report Reminder'), ('analysis_reminder', 'Analysis Report Reminder')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_remove_on_completion', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='dashboard_n_user_id_b572f4_idx'), models.Index(fields=['notification_type', 'created_at'], name='dashboard_n_notific_681652_idx')],
            },
        ),
    ]
