# Generated by Django 5.1.1 on 2025-08-16 14:47

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('nrp', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('admin', 'Admin'), ('foreman', 'Foreman')], default='foreman', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('SUPPORT', 'Support $ Fabrikasi'), ('TRACK', 'Track'), ('PLANT', 'Plant Coal Hauling'), ('WHEEL', 'Wheel')], max_length=100, null=True)),
                ('shift', models.IntegerField(choices=[(1, 'Shift 1'), (2, 'Shift 2')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.IntegerField(choices=[(1, 'Shift 1'), (2, 'Shift 2')], default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('activities', models.TextField()),
                ('leader', models.CharField(blank=True, choices=[('Leader_1', 'YUDI SULISTIYONO'), ('Leader_2', 'DWI ARI PRASETYA'), ('Leader_3', 'ADI RIYANTO'), ('Leader_4', 'MOH FADHOLI')], max_length=100, null=True)),
                ('Unit_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Hmkm', models.CharField(blank=True, max_length=100, null=True)),
                ('component', models.CharField(blank=True, choices=[('Component_1', 'Engine'), ('Component_2', 'Clutch - Couper'), ('Component_3', 'PTO'), ('Component_4', 'Transmisi'), ('Component_5', 'Final Drive'), ('Component_6', 'Travel - Axle'), ('Component_7', 'Steering'), ('Component_8', 'Under Carriage'), ('Component_9', 'Wheel'), ('Component_10', 'Frame & Guard'), ('Component_11', 'Electric'), ('Component_12', 'Brake'), ('Component_13', 'Suspension'), ('Component_14', 'Hydraulic'), ('Component_15', 'Pneumatic'), ('Component_16', 'Swing System'), ('Component_17', 'Attachment'), ('Component_18', 'GET'), ('Component_19', 'Vessel Assy'), ('Component_20', 'Generating Set'), ('Component_21', 'Dewatering Pump'), ('Component_22', 'Optional Accessories'), ('Component_23', 'Tank & Piping'), ('Component_24', 'AC'), ('Component_25', 'Stone Crusher'), ('Component_26', 'Daily Maintenance'), ('Component_27', '12 Mounth Service'), ('Component_28', '6 Mounth Service'), ('Component_29', '90 Days Service'), ('Component_30', '30 Days Service'), ('Component_31', '10 Dayts Service'), ('Component_32', 'PPA'), ('Component_33', 'PPU'), ('Component_34', 'PPM'), ('Component_35', 'PAP'), ('Component_36', '4000 Hour Service'), ('Component_37', '2000 Hour Service'), ('Component_38', '1000 Hour Service'), ('Component_39', '500 Hour Service'), ('Component_40', '250 Hour Service'), ('Component_41', '100 Hour Service (Inisial)'), ('Component_42', '50 Hour Service (inisial)'), ('Component_43', '100 Hour Dialy Check'), ('Component_44', 'Component Overhaul'), ('Component_45', 'Component Midlive'), ('Component_46', '20.000 KM Service'), ('Component_47', '15.000 KM Service'), ('Component_48', '10.000 KM Service'), ('Component_49', '5.000 KM Service'), ('Component_50', '2.500 KM Service')], max_length=100, null=True)),
                ('activities_code', models.CharField(blank=True, choices=[('SC', 'SC'), ('USC', 'USC'), ('ACD', 'ACD')], max_length=100, null=True)),
                ('foreman', models.ForeignKey(limit_choices_to={'role': 'foreman'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
