# Generated by Django 5.1.1 on 2025-09-30 07:56

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='dokumentasi_sebelum',
            field=models.FileField(blank=True, help_text='Upload gambar/drawing sebelum perbaikan (Max 1MB)', null=True, upload_to=dashboard.models.analysis_report_upload_path, verbose_name='Dokumentasi Sebelum'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='dokumentasi_sesudah',
            field=models.FileField(blank=True, help_text='Upload gambar/drawing sesudah perbaikan (Max 1MB)', null=True, upload_to=dashboard.models.analysis_report_upload_path, verbose_name='Dokumentasi Sesudah'),
        ),
    ]
