# Generated by Django 5.1.1 on 2025-09-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='section_track',
            field=models.CharField(blank=True, choices=[('PC1250', 'PC1250'), ('CAT395', 'CAT395'), ('DX800', 'DX800'), ('PC500', 'PC500'), ('PC300', 'PC300'), ('PC200/210', 'PC200/210'), ('D375', 'D375'), ('D155', 'D155'), ('D85', 'D85'), ('EPIROC DM30', 'EPIROC DM30'), ('HD785', 'HD785'), ('VOLVO FMX400', 'VOLVO FMX400'), ('GD955', 'GD955'), ('GD535', 'GD535'), ('GD160K/M', 'GD160K/M'), ('DYNAPAC COMPACTOR', 'DYNAPAC COMPACTOR'), ('HD465/WT', 'HD465/WT'), ('RENAULT FT/LB', 'RENAULT FT/LB'), ('HINO WT/LT/CT', 'HINO WT/LT/CT'), ('MANITAOU', 'MANITAOU'), ('KATO CRANE', 'KATO CRANE'), ('GENSET', 'GENSET'), ('WATER PUMP (WP)', 'WATER PUMP (WP)'), ('HINO DT', 'HINO DT'), ('MERCY DT', 'MERCY DT'), ('BOMAG COMPACTOR', 'BOMAG COMPACTOR')], max_length=100, null=True),
        ),
    ]
