# Generated by Django 5.1.1 on 2025-08-18 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_track', models.CharField(blank=True, choices=[('PC1250', 'PC1250'), ('CAT395', 'CAT395'), ('DX800', 'DX800'), ('PC500', 'PC500'), ('PC300', 'PC300'), ('PC200/210', 'PC200/210'), ('D375', 'D375'), ('D155', 'D155'), ('D85', 'D85'), ('EPIROC DM30', 'EPIROC DM30')], max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('no_report', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.DateField()),
                ('WO_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('WO_date', models.DateField()),
                ('unit_code', models.CharField(blank=True, max_length=100, null=True)),
                ('problem', models.CharField(blank=True, choices=[('1000', 'Engine'), ('2000', 'Clutch System'), ('3000', 'Transmission'), ('4000', 'Travel Dive-Axle'), ('5000', 'Steering'), ('6000', 'Undercariage'), ('7000', 'Electric'), ('8000', 'Attachment'), ('9000', 'Periodical Services')], max_length=100, null=True)),
                ('Trouble_date', models.DateField()),
                ('Hm', models.CharField(blank=True, max_length=100, null=True)),
                ('title_problem', models.TextField()),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('part_name', models.CharField(blank=True, max_length=100, null=True)),
                ('foreman', models.ForeignKey(limit_choices_to={'role': 'foreman'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('activity_reminder', 'Activity Report Reminder'), ('analysis_reminder', 'Analysis Report Reminder')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_remove_on_completion', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='dashboard_n_user_id_b572f4_idx'), models.Index(fields=['notification_type', 'created_at'], name='dashboard_n_notific_681652_idx')],
            },
        ),
    ]
