# Generated by Django 5.1.1 on 2025-09-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_analysisreport_dokumentasi_sebelum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisreport',
            name='dokumentasi_sebelum',
        ),
        migrations.RemoveField(
            model_name='analysisreport',
            name='dokumentasi_sesudah',
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='dokumentasi_sebelum_content_type',
            field=models.CharField(blank=True, help_text='Content type gambar sebelum (image/jpeg, image/png, dll)', max_length=100, null=True, verbose_name='Content Type Sebelum'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='dokumentasi_sebelum_data',
            field=models.BinaryField(blank=True, help_text='Data binary gambar sebelum perbaikan', null=True, verbose_name='Data Gambar Sebelum'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='dokumentasi_sebelum_filename',
            field=models.CharField(blank=True, help_text='Nama file gambar sebelum perbaikan', max_length=255, null=True, verbose_name='Nama File Sebelum'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='dokumentasi_sesudah_content_type',
            field=models.CharField(blank=True, help_text='Content type gambar sesudah (image/jpeg, image/png, dll)', max_length=100, null=True, verbose_name='Content Type Sesudah'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='dokumentasi_sesudah_data',
            field=models.BinaryField(blank=True, help_text='Data binary gambar sesudah perbaikan', null=True, verbose_name='Data Gambar Sesudah'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='dokumentasi_sesudah_filename',
            field=models.CharField(blank=True, help_text='Nama file gambar sesudah perbaikan', max_length=255, null=True, verbose_name='Nama File Sesudah'),
        ),
    ]
