# Generated by Django 5.1.1 on 2025-09-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_analysisreport_section_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='faktor_environment',
            field=models.TextField(blank=True, help_text='Jelaskan faktor lingkungan yang berkontribusi terhadap masalah', null=True, verbose_name='Environment (Lingkungan)'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='faktor_machine',
            field=models.TextField(blank=True, help_text='Jelaskan faktor mesin yang berkontribusi terhadap masalah', null=True, verbose_name='Machine (Mesin)'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='faktor_man',
            field=models.TextField(blank=True, help_text='Jelaskan faktor manusia yang berkontribusi terhadap masalah (contoh: Terjadi kelalaian pada saat monitoring)', null=True, verbose_name='Man (Manusia)'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='faktor_material',
            field=models.TextField(blank=True, help_text='Jelaskan faktor material yang berkontribusi terhadap masalah', null=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='faktor_method',
            field=models.TextField(blank=True, help_text='Jelaskan faktor metode yang berkontribusi terhadap masalah', null=True, verbose_name='Method (Metode)'),
        ),
    ]
