# Generated by Django 5.1.1 on 2025-09-30 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_analysisreport_dokumentasi_sebelum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Tanggal jadwal shift')),
                ('shift', models.IntegerField(choices=[(1, 'Shift 1'), (2, 'Shift 2')], help_text='Shift yang ditugaskan (1 atau 2)')),
                ('department', models.CharField(choices=[('SUPPORT', 'Support & Fabrikasi'), ('TRACK', 'Track'), ('PLANT', 'PCH'), ('WHEEL', 'Wheel')], help_text='Departemen foreman', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Status aktif jadwal')),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan untuk jadwal ini', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin yang membuat jadwal', limit_choices_to={'role__in': ['admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('foreman', models.ForeignKey(help_text='Foreman yang dijadwalkan', limit_choices_to={'role': 'foreman'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jadwal Shift',
                'verbose_name_plural': 'Jadwal Shift',
                'ordering': ['-date', 'shift'],
                'indexes': [models.Index(fields=['date', 'shift'], name='dashboard_s_date_dc5ce6_idx'), models.Index(fields=['foreman', 'date'], name='dashboard_s_foreman_5207a4_idx')],
                'unique_together': {('date', 'foreman')},
            },
        ),
    ]
