# Generated by Django 5.1.1 on 2025-09-20 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_analysisreport_faktor_environment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='dashboard_n_user_id_b572f4_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Notifikasi akan otomatis dihapus setelah tanggal ini', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='Notifikasi yang dikirim manual oleh admin'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='requires_acknowledgment',
            field=models.BooleanField(default=False, help_text='Memerlukan konfirmasi dari user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('acknowledged', 'Acknowledged')], default='unread', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram Chat ID untuk notifikasi', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('activity_reminder', 'Activity Report Reminder'), ('analysis_reminder', 'Analysis Report Reminder'), ('manual_message', 'Manual Message'), ('system_alert', 'System Alert'), ('deadline_warning', 'Deadline Warning')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin'), ('leader', 'Leader'), ('foreman', 'Foreman')], default='foreman', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status'], name='dashboard_n_user_id_239581_idx'),
        ),
    ]
