# Generated by Django 5.1 on 2025-10-01 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_shiftschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShiftSchedule',
        ),
    ]
