# Generated by Django 5.1.1 on 2025-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_recreate_shiftschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='section',
            field=models.CharField(choices=[('SUPPORT', 'Support & Fabrikasi'), ('TRACK', 'Track'), ('PLANT', 'PCH'), ('WHEEL', 'Wheel')], help_text='Section/Track', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin'), ('leader', 'Leader'), ('mekanik', 'Mekanik')], default='foreman', max_length=20),
        ),
    ]
