# Generated by Django 5.1.1 on 2025-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_activityreport_section_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin'), ('leader', 'Leader'), ('foreman', 'Foreman')], default='foreman', max_length=20),
        ),
    ]
